# The Steepener Trade

## Data Imports

In [3]:
import pandas as pd

#DATE = '2023-06-30'
DATE = '2024-01-02'

FILE_DATA = f'../data/steepener_trade_{DATE}.xlsx'

info = pd.read_excel(FILE_DATA,sheet_name='info').set_index('KYTREASNO').T
clean = pd.read_excel(FILE_DATA,sheet_name='clean price').set_index('quote date')
dirty = pd.read_excel(FILE_DATA,sheet_name='dirty price').set_index('quote date')
duration = pd.read_excel(FILE_DATA,sheet_name='duration').set_index('quote date')

print("Dirty Prices:")
display(dirty)
print("Duration:")
display(duration)

Dirty Prices:

               207652      208147
quote date
2023-11-09  90.978261   99.000000
2023-11-10  90.940217   98.789062
2023-11-13  91.005774   98.882812
2023-11-14  91.397418  100.414062
2023-11-15  91.253906   99.742188
...               ...         ...
2025-05-23  97.904452  100.762021
2025-05-27  97.907937  101.224864
2025-05-28  97.913829  100.967561
2025-05-29  97.917768  101.397758
2025-05-30  97.949000  101.685377

[388 rows x 2 columns]

Duration:

              207652    208147
quote date
2023-11-09  2.135193  8.173725
2023-11-10  2.132450  8.168483
2023-11-13  2.124233  8.160898
2023-11-14  2.121523  8.174992
2023-11-15  2.118771  8.164722
...              ...       ...
2025-05-23  0.607258  7.147798
2025-05-27  0.596299  7.140169
2025-05-28  0.593559  7.135270
2025-05-29  0.590819  7.135881
2025-05-30  0.588080  7.135339

[388 rows x 2 columns]

### 1.1
- 50 million long in the 2 year bond

In [ ]:
long_position = 50*(10**7)  # $50 million
interest_ratio = duration.loc['2023-11-09',:].loc[207652] * dirty.loc['2023-11-09',:].loc[207652] / (duration.loc['2023-11-09',:].loc[208147] * dirty.loc['2023-11-09',:].loc[208147])
short_dollar = long_position * interest_ratio
print(f"short_dollar: {short_dollar}")
two_year_bond = long_position / dirty.loc['2023-11-09',:].loc[207652]
print(f"two_year_bond: {two_year_bond}")
ten_year_bond = short_dollar / dirty.loc['2023-11-09',:].loc[208147]
print(f"ten_year_bond: {ten_year_bond}")

short_position: 13061324.114895342
ten_year_bond: 131932.56681712467
two_year_bond: 5495818.399044205